# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170119_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'get_latest_by': 'publication_date', 'ordering': ['tree_id', 'lft'], 'permissions': [('can_freeze', 'Can freeze page'), ('can_publish', 'Can publish page'), ('can_manage_en_us', 'Manage US English')], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='sites',
        ),
        migrations.AlterField(
            model_name='media',
            name='extension',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_pages', to='pages.Page', verbose_name='redirect to'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_to_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='redirect to url'),
        ),
    ]
