# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190801_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'get_latest_by': 'publication_date', 'ordering': ['tree_id', 'lft'], 'permissions': [('can_freeze', 'Can freeze page'), ('can_publish', 'Can publish page'), ('can_manage_ru', 'Manage Russian')], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AddField(
            model_name='content',
            name='label',
            field=models.CharField(default=1, max_length=100, verbose_name='label'),
            preserve_default=False,
        ),
    ]
