# Generated by Django 2.2.15 on 2020-09-01 10:48

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20181102_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='label',
            field=models.CharField(default=1, max_length=100, verbose_name='label'),
            preserve_default=False,
        ),
    ]
