# Generated by Django 2.2.24 on 2021-12-20 11:31

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200901_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'media', 'verbose_name_plural': 'medias'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'get_latest_by': 'publication_date', 'ordering': ['tree_id', 'lft'], 'permissions': [('can_freeze', 'Can freeze page'), ('can_publish', 'Can publish page'), ('can_manage_ru', 'Manage Russian')], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='pagealias',
            options={'verbose_name': 'alias', 'verbose_name_plural': 'aliases'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='sites',
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='media',
            name='extension',
            field=models.CharField(blank=True, editable=False, max_length=32, verbose_name='extension'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.FileField(upload_to=pages.models.media_filename, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='freeze_date',
            field=models.DateTimeField(blank=True, help_text="Don't publish any content after this date.", null=True, verbose_name='freeze date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publication_date',
            field=models.DateTimeField(blank=True, help_text='When the page should go live. Status must be "Published" for page to go live.', null=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publication_end_date',
            field=models.DateTimeField(blank=True, help_text='When to expire the page. Leave empty to never expire.', null=True, verbose_name='publication end date'),
        ),
    ]
